### ISSUE TITLE
Roadmap - Webframe 2.0

### ISSUE THREAD

**Issue by calummoore** [1productaweek/webframe#2]
Hi everyone 👋

I'm going to be working on Webframe for another week (at some point in the near future), and wanted to document the feature requests we've had so far. I'm also going to be sending an e-mail out to everyone who signed up for their feedback/ideas - so this may change. If you have ideas please comment below!

#### Minor updates
- [ ] Mobile improvements
   - [ ] Put navigation in sidebar on mobile

- [ ] UX improvements
   - [ ] Sticky header nav (only when scrolling back up!)
   - [ ] Back to top button
   - [ ] Add next / previous btns when in Modal view
  
- [ ] SEO / Social improvments
   - [ ] Make each screenshot a separate page (but also keep the modal)
   - [ ] Add a share button to each image
   - [ ] Add descriptions for each category

#### Major updates
- [ ] Chrome extension - would enable users to upload screens to Webframe and add a 
- [ ] Components - allow people to select interesting parts of an image to be labeled and 
- [ ] Search + Categories - add search to the site, allow categories to be user submitted
- [ ] Flows - allow screens to be grouped into logical flows (e.g. similar pages, intro screen sequences)
- [ ] Monetization - how could we generate an income for Webframe to help support the on-going running of the site?

**Comment by sourabh2k15** [comment]
would like to work on a chrome extension, as per my understanding I just need an extension that allows users to take a screenshot and then I can make a POST / GET to an endpoint that would upload it to webframe right ? I am assuming the endpoint already exists so it's just the screenshot functionality I need to build ?

**Comment by calummoore** [comment]
@sourabh2k15 I've created a new issue to discuss this further 👍🏽https://github.com/1productaweek/webframe/issues/3
